export default {
  //ACTIONS
  TAKING_SEAT: 'TAKING_SEAT',
  BATTLEROOMS_RECEIVE_DATA: 'BATTLEROOMS_RECEIVE_DATA',
  BATTLEROOMS_RECEIVE_DATA_ERROR: 'BATTLEROOMS_RECEIVE_DATA_ERROR',
  //STATES
  ON_SEAT: 'ON_SEAT',
}
