export default {
  //actions
  INITIALIZE_BATTLE: 'INITIALIZE_BATTLE',
  TERMINATE_BATTLE: 'TERMINATE_BATTLE',
  LOAD_INITIAL_BATTLE_STAGE: 'LOAD_INITIAL_BATTLE_STAGE',
  SYNC_BATTLE: 'SYNC_BATTLE',
  STOP_LISTENING_BATTLE: 'STOP_LISTENING_BATTLE',
}
