export default {
  //ACTIONS
  TAKING_SEAT: 'TAKING_SEAT',
  LEAVING_SEAT: 'LEAVING_SEAT',
  SEAT_STATUS_RECEIVE: 'SEAT_STATUS_RECEIVE',
  BATTLEROOMS_RECEIVE_DATA: 'BATTLEROOMS_RECEIVE_DATA',
  BATTLEROOMS_RECEIVE_DATA_ERROR: 'BATTLEROOMS_RECEIVE_DATA_ERROR',
  //STATES
  ON_SEAT: 'ON_SEAT',
  LEFT_SEAT: 'LEFT_SEAT',
}
