export default {
  // ACTIONS
  GET_POKEMON: 'GET_POKEMON',
  SELECT_POKEMON: 'SELECT_POKEMON',
  SAVE_POKEMON: 'SAVE_POKEMON',
  // STATES
  GET_POKE_FAILED: 'GET_POKE_FAILED',
  FIREBASE_TRAINER_INITIALIZE_BEGIN: 'FIREBASE_TRAINER_INITIALIZE_BEGIN',
  INITIALIZE_TRAINER_SUCCEED: 'INITIALIZE_TRAINER_SUCCEED',
  INITIALIZE_TRAINER_FAILED: 'INITIALIZE_TRAINER_FAILED',
};
